version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  web:
    build: .
    restart: always
    ports:
      - 3000:3000
    links:
      - db
    environment:
      MONGO_DATABASE_URL: mongodb+srv://root:root@cluster0.yfx9l.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      DATABASE_URL: postgres://root:example@db:5432/root
      DB: mongo
